Repository php-db/phpdb, pull requests merged in 2025-03, with the labels that each got.

#26 Updating dependencies
  composer.json
Labels: qa

#30 Add a Docker configuration
  README.md
  Vagrantfile
  bin/install-deps.sh
  compose.yml
  docker/databases/mysql/Dockerfile
  docker/databases/postgresql/Dockerfile
  docker/php/Dockerfile
  docker/php/conf.d/error_reporting.ini
  docker/php/conf.d/xdebug.ini
  phpunit.xml.dist
  test/integration/TestFixtures/mysql.sql
  test/integration/TestFixtures/pgsql.sql
Labels: enhancement

#27 set-psalm-baseline
  .psr-container.php.stub
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml.dist
Labels: qa

#31 Returns package name to laminas/laminas-db so an vcs override can be …
  composer.json
Labels: bug

#32 Refactor test code to support PHPUnit's new event system
  phpunit.xml.dist
  test/integration/Extension/IntegrationTestStartedListener.php
  test/integration/Extension/IntegrationTestStoppedListener.php
  test/integration/Extension/ListenerExtension.php
Labels: enhancement, qa

#36 Most recent revisions
  src/Adapter/AbstractAdapter.php
  src/Sql/AbstractPreparableSql.php
  src/Sql/Platform/AbstractPlatform.php
  src/Sql/Platform/Platform.php
  src/Sql/PreparableSqlInterface.php
  src/Sql/Sql.php
Labels: qa

#37 Update MySQL Docker base image
  compose.yml
  docker/databases/mysql/Dockerfile
Labels: enhancement
